[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "menanam_ai"
readme = "README.md"
dynamic = [
    "version",
]
dependencies = [
    "ipython>=8.10",
    "jupyterlab>=3.0",
    "notebook",
    "kedro[jupyter]~=1.4.0",
    "kedro-datasets[pandas-csvdataset, pandas-exceldataset, pandas-parquetdataset, plotly-plotlydataset, plotly-jsondataset, matplotlib-matplotlibdataset]>=3.0",
    "kedro-viz>=6.7.0",
    "scikit-learn~=1.5.1; python_version <= '3.10'",
    "scikit-learn~=1.8.0; python_version > '3.10'",
    "seaborn~=0.12.1",
]

[project.scripts]
menanam-ai = "menanam_ai.__main__:main"

[project.entry-points."kedro.hooks"]

[tool.setuptools.dynamic.version]
attr = "menanam_ai.__version__"

[tool.setuptools.packages.find]
where = [
    "src",
]
namespaces = false

[tool.kedro]
package_name = "menanam_ai"
project_name = "Menanam AI"
kedro_init_version = "1.4.0"
tools = "['None']"
example_pipeline = "True"
source_dir = "src"
